default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8
  collation: utf8mb4_general_ci
  database: abedayama_development
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: <%= ENV['DATABASE_SOCKET'] %>

development:
  <<: *default

test:
  <<: *default
  database: abedayama_test

production:
  <<: *default
